### ISSUE TITLE
[DEMO] NHS Portal

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.web#10]
1) NHS Landing page
![2_system_2](https://cloud.githubusercontent.com/assets/5257001/24298452/b3834bc6-10ae-11e7-9df3-7068bf096864.png)
2) Медичні заклади - change all the logos with the geometric figures.
![1_main](https://cloud.githubusercontent.com/assets/5257001/24298476/ca8bc1a4-10ae-11e7-9b52-b13be5adb963.png)
3) Реєстрація клініки
https://www.dropbox.com/s/s8ch20j9jbak9bh/Create_clinic_s1.jpg?dl=0
https://www.dropbox.com/s/d2tu40xyw4m83vd/Create_clinic_s2.jpg?dl=0
https://www.dropbox.com/s/iermkq7rp645wnj/Create_clinic_s3.jpg?dl=0
4) Накласти ЕЦП - standard popup.

**Comment by ivchenkodima** [comment]
done
