### ISSUE TITLE
[DEMO] Create Declaration. Adjustments

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.web#17]
1. Rename "Адреса проживання Пацієнта" to "Адреса надання медичних послуг"
2. Add checkbox "Відмовляюсь від надання допомоги за місцем проживання (перебування)" after "Адреса надання медичних послуг"
3. Add "Слово-пароль" field after email
4. Add "Контакти особи на випадок екстреної ситуації" block just after addresses:
- Прізвище
- Ім'я
- По батькові
- телефон

**Comment by ivchenkodima** [comment]
done
https://prm-web-pr-19.herokuapp.com/declaration/
