### ISSUE TITLE
[Demo] Register new Declaration screen flow

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.web#2]
Implement the below [screen-flow](https://edenlab.atlassian.net/wiki/display/EH/MIS+Screen+flow):

1. Register Declaration Step 1
2. Additional Search Parameter screen. Should be shown only in case if search returns >1 records
3. Register Declaration Step 2
4. Declaration Authorization screen
5. Sign off declaration. 
6. Success

[Reference design](https://marvelapp.com/1f3ac88/screen/25829276) for some pages only! In case of mismatch we should use the confluence source as the main one.

**Comment by ivchenkodima** [comment]
done
