### ISSUE TITLE
[DEMO] overall comments

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.web#27]
1. Реєстр лікарів - Забити константами список лікарів
    1. ID
    2. Name - ім’я
    3. Birthdate - дата народження
    4. Speciality - Спеціальність
    5. Status - Статус
2. Декларація - Додати nationalID
3. Підписувати можна тільки Декларації в статусі “Не підписано”
5. Клініка - учасники -додати кнопку add item
6. Масив відокремлених підрозділів - додати кнопку add item
7. Реєстрація клініки - Прибрати поле тип контакту  
8. Реєстрація клініки - Додати попап - Підпис медзаклкду
9. Попап підпису - додати загрузку файлу сертифікату
10. Поправити атрибути лікаря
    1.  Прибрати адреси
    2. Поправити атрибути
11. Додати кнопку “додати опікуна”
12. sort declarations by created date
13. Розрахунки - переіменувати на “Статистика”
14. Статистика - Додати поле к-ть декларацій - total declarations
15. Виправити послідовність сторінок порталу НСЗ

**Comment by ivchenkodima** [comment]
done
