### ISSUE TITLE
[DEMO] overall comments

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.web#35]
1. Пофіксити кнопки назад на формі “Підписати декларацію”
2. Заповнити дефолтними значеннями форму створення декларації - як мінімум обов’язкові поля
3. Створити лікаря
    1. В блок ‘Професійний рівень’ Додати поле “Спеціальність”. ENUM('терапевт', 'педіатр', 'сімейний лікар')
    2. Змінити послідовність блоків:
        1. Блок  ‘Професійний рівень’
        2. Блок “Наукова ступінь”
        3. Блок “Академічна ступінь”
        4. Блок “Інформація про освіту”
        5. Блок “Кваліфікація”
        6. Блок “Досвід роботи”
    3. Інформація про освіту - масив, додати кнопку ‘Додати освіту’
    4. Досвід роботи - масив, додати кнопку ‘Додати роботу’
    5. Кваліфікація - масив, додати кнопку ‘Додати кваліфікацію’
4. Створення декларації - номер мобільного телефону не копіюється з форми пошуку
5. Кнопка "Нова декларація" в результатах пошуку декларації не працює коректно 
<img width="514" alt="screen shot 2017-04-03 at 9 32 49 am" src="https://cloud.githubusercontent.com/assets/5257001/24597787/894f1bb0-1850-11e7-9396-b488932fb99d.png">

**Comment by ivchenkodima** [comment]
done
