### ISSUE TITLE
[DEMO] Create declaration fixes

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.web#5]
1. add dropdown with the doctor's list - 
    1. http://docs.ehealthapi1.apiary.io/#reference/partnership-relations-management/doctors/search-for-a-doctor
    2. http://104.155.75.171/api/doctors
2. Change the control "загрузки ЕЦП" to load *.cert file
3. Mask the key password field.

**Comment by ivchenkodima** [comment]
done
