### ISSUE TITLE
[DEMO] Register a Doctor screen-flow

### ISSUE THREAD

**Issue by lymychp** [Nebo15/prm.web#6]
Implement screens only, no BE integration
https://edenlab.atlassian.net/wiki/display/EH/MIS+Screen+flow
https://www.dropbox.com/s/uuf82yvb35ora1a/Create_doc_s1.jpg?dl=0
https://www.dropbox.com/s/5refaku0hx1vpjh/Create_doc_s2.jpg?dl=0

**Comment by ivchenkodima** [comment]
done
